### ISSUE TITLE
Aquaero 6 support checklist

### ISSUE THREAD

**Issue by aleksamagicka** [aleksamagicka/aquacomputer_d5next-hwmon#16]
Tracking work related to the [aquaero6lt](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/tree/aquaero6lt) branch:

- [ ] Getting product IDs of the other two variants (if they are different) and testing them
- [ ] Reading temperature sensors
- [ ] Initializing only the "aquaero Device" HID device, out of the three (the rest being "aquaero keyboard/mouse" and "aquaero System Control" - these names are visible from monitoring software on Windows) that aquaero creates
- [ ] Reading fan PWM values
- [ ] Writing to fan PWM values
- [ ] Reading/writing fan curves (?)
- [ ] And perhaps, investigating the similarities between aquaero 5 and 6

**Comment by aleksamagicka** [comment]
It has been [confirmed](https://www.reddit.com/r/watercooling/comments/wezumm/aquaero_6_xt_and_pro_variants_usb_product_ids/) that all Aquaero 6 variants (LT, Pro, XT) are the same base with added daughter boards (for example, screen with buttons) - so their ID is `F001`.

From the thread, Aquaero _5_ LT also has the same ID, which ties into what I read - that the Aquaero 6 is just a beefed up Aquaero 5 with better power delivery (or similar). Either way, seems like differentiating between Aquaero 5 and 6 is not needed, but that's out of scope for this issue anyhow.

**Comment by Obmawo** [comment]
hi,

thank you for this awesome project.
can you add support for the flow sensor on the aquaero 6, too?

**Comment by aleksamagicka** [comment]
I would gladly, but I don't have one myself. Added that to the checklist above.

**Comment by Obmawo** [comment]
Maybe I can help you. I have this hardware and optional CaliTemp Sensors.

**Comment by aleksamagicka** [comment]
If you'd want to try, you'll need to capture the HID reports Aquaero is sending to the host (your PC) every second, and find where the flow sensor value is located (at which offset, best done in a hex editor). You can do that by using Wireshark (here's a [general tutorial](https://github.com/liquidctl/liquidctl/blob/main/docs/developer/capturing-usb-traffic.md)) or some other software.

**Comment by DrTron** [comment]
Regarding the additional outputs of an aquaero (flow, reservoir level, power, etc.), you may want to take a peek here. That guy has already figured out the offsets of the different values:
https://github.com/shred/pyquaero

**Comment by aleksamagicka** [comment]
No problem. I'll be able to look into it in a few days, hopefully, but I'm always there for help & discussions.

**Comment by DrTron** [comment]
Ok, so here's what I get from the driver. I did compile it for a 5.10 kernel, so without hwmon_pwm_auto_channels_temp, if that's relevant.
My setup is: aquaero5, 4 3-pin fans, 5 temperature sensors, 1 flow sensor, AquastreamXT pump.
The aquastream is not detected at all. I'll compare the aquaero data to the data that pyquaero is able to extract.

aquaero-hid-3-191b
Adapter: HID adapter
Fan 1 voltage:            6.00 V  (wrong)
Fan 2 voltage:            3.98 V  (correct)
Fan 3 voltage:            8.48 V  (wrong)
Fan 4 voltage:            0.00 V  (wrong)
Fan 1 speed:            32767 RPM  (wrong, obviously)
Fan 2 speed:             581 RPM  (correct)
Fan 3 speed:             401 RPM  (wrong, should be 600)
Fan 4 speed:               0 RPM  (wrong)
Flow sensor 1 [dL/h]:      0 RPM 
Flow sensor 2 [dL/h]:   28210 RPM (wrong, flow should be around 50L/h or 500dL/h)
Sensor 1:               +268.9°C  (wrong)
Sensor 2:               +238.0°C  (wrong)
Sensor 3:                +23.9°C  
Sensor 4:                +24.6°C  
Sensor 5:                +25.4°C  
Sensor 6:                +23.9°C  
Sensor 7:                +23.2°C  (Sensor 3-7 seem to be 1-5 in reality, but the values seem ok)
Sensor 8:                    N/A  
Virtual sensor 1:            N/A  
Virtual sensor 2:            N/A  
Virtual sensor 3:            N/A  
Virtual sensor 4:            N/A  
Virtual sensor 5:            N/A  
Virtual sensor 6:            N/A  
Virtual sensor 7:            N/A  
Virtual sensor 8:            N/A  
Calc. virtual sensor 1:      N/A  
Calc. virtual sensor 2:      N/A  
Calc. virtual sensor 3:   +0.8°C  (correct, that is my water temperature delta-T, but it should be virtual sensor 1)
Calc. virtual sensor 4:      N/A  
Fan 1 power:              3.97 W  
Fan 2 power:              5.97 W  
Fan 3 power:              4.20 W  
Fan 4 power:              0.00 W  (all fan powers seem off, should be less than 1W since they all run at around 4V)
Fan 1 current:            3.30 A  
Fan 2 current:            0.00 A  
Fan 3 current:            3.50 A  
Fan 4 current:            0.00 A  (same here, way too high or zero)

Fields that pyquaero populates additionally:
Fan power in percent (as set by the aquaero)
Reservoir levels (as mentioned, but I don't have any installed)
Aquaero chip temperature
Fan VRM temperatures

Hope that helps!

**Comment by aleksamagicka** [comment]
I also suspect the aquaero differences are due to firmware. As for aquabus, that's not implemented. I don't think I have the cables and even any devices for that at all, so I'm of no help in that regard. (I have the d5 next, octo, quadro, farbwerk 360 and aquaero 6, for reference.)

**Comment by DrTron** [comment]
Thanks!
As for the aquabus, the devices connected to it are visible to the aquaero, and can be read through it. So it's possible.
I'll certainly volunteer for testing.
But like I mentioned, the pyquaero maintainer already figured out at which address which value is, if that's what's needed: https://github.com/shred/pyquaero/blob/master/pyquaero/struct/struct1200.py

**Comment by DrTron** [comment]
So I upgraded the firmware of both my aquaero 5s (to 2104) and both are working. The only difference I notice is that both report fan rpm and voltage, but only one of them reports fan amperage and thus power, and only 3/4.
Aquaero 1 has 4 3-pin fans connected, and only fan 1, 3 & 4 show amperage and power.
Aquaero 2 has 2 3-pin fans and 1 4-pin fan connected, and none of them show amperage and power.

Voltage and speed is correct for all fans.

Not a big deal, just wanted to share.

**Comment by DrTron** [comment]
Update after git pull:
- aquaero1 (v5 Pro, on kernel 5.10.0-23-amd64) is now showing all the fans' amperage and power correctly
- aquaero2 (v5 LT, on kernel 6.2.0-20-generic) is still showing zeroes for all fans' amperage and power
- connected aquabus devices on aquaero1 show correct values
Both aquaeros are on the same firmware (2104).

**Comment by aleksamagicka** [comment]
Thanks, I've opened a new issue to track the second point.

**Comment by uday7981** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
noda-sin, @mwerezak, @gcobcqwe, @grozmus, @ph03, @bravoila, @jdaaph, @Karlheinzniebuhr, @cwcheak, @kessler, @7s4r, @zhouchengming1, @marcusmonteiro, @tatoalo, @kallolpar, @jaggedsoft, @80000v, @wingofsky, @dzhlovegithub, @coodered

**Comment by aleksamagicka** [comment]
(If anyone received a message offering a Developer position at Github, know that it's a scam.)

**Comment by DrTron** [comment]
Thanks for the Heads-Up, but yes, it already pretty much looked like one 
;-)

> (If anyone received a message offering a Developer position at Github, 
> know that it's a scam.)
> 
> --
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: 
> ***@***.***>


-- 
Yours,
Michael
