### ISSUE TITLE
Upstreaming progress

### ISSUE THREAD

**Issue by aleksamagicka** [aleksamagicka/aquacomputer_d5next-hwmon#81]
This issue is used to track features that are not yet upstreamed into the kernel.

---

Devices:

- [ ] Leakshield - setting parameters
- [ ] Aquastream XT - setting speeds
- [ ] Aquaero - pwmX_mode + hw_version - #84 
- [ ] Aquaero - total and current uptime
- [ ] Aquaero - aquabus
- [ ] Aquaero - fan min/max
- [ ] Aquaero - anything else?
- [ ] pwm_enable
- [ ] Temp-PWM curves (D5 Next, Quadro, Octo)
- [x] Ctrl report -EPIPE fix (#86)
- [ ] hwmon_pwm_auto_channels_temp
- [x] High Flow USB sensors (#93)

Docs:

- [ ] Remove outdated stuff from mainline docs

**Comment by nyabinary** [comment]
Any update on this :3 wha not exactly mainlined yet?

**Comment by aleksamagicka** [comment]
Mostly that above, I think. I'll try to get more upstreamed till EOY.

**Comment by nyabinary** [comment]
> Mostly that above, I think. I'll try to get more upstreamed till EOY.

Also saw this https://github.com/liquidctl/liquidctl/pull/534 will this be worked on after this?

**Comment by aleksamagicka** [comment]
One day ;)
